
modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Unlicense"

[[mods]] #mandatory
modId="galenacapes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Galena Capes" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://discord.gg/JmMf7CEKsx" #optional
logoFile="icon.png" #optional
credits="Thanks to our Patreon supporters who help us maintain and make our mods!" #optional
authors="Xaidee as part of Team Galena" #optional
description='''
A client side mod used to display unique capes on our lovely patreon members and developers!
'''
[[dependencies.galenacapes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.galenacapes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
